# SID Information
nodes:
    - name: Com1 
      sid: fc00:1::/64
    - name: Com2 
      sid: fc00:2::/64
    - name: Com3 
      sid: fc00:3::/64
    - name: Com4 
      sid: fc00:4::/64

# System Infomation
system:
    # Measurement node 
    mm_src_node: Com1
    # Available address ranges
    available_addr_range: 
        start: fd00:0:172:16:ffff::1
        end: fd00:0:172:16:ffff::ffff
    # Encap rules: Describe the path you want to measure in the sid_list
    encap_rules:
        - mm_dst_node: Com4
          seg_func: encap
          sid_list: Com2
        - mm_dst_node: Com4
          seg_func: encap
          sid_list: Com3 
        - mm_dst_node: Com4
          seg_func: encap
          sid_list: com2, Com3

# Estimete Parameter
param:
    method: ptr
    packet_num: null
    packet_size: null
    repeat_num: null
