# SID Information
nodes:
    - host: Compute1 
      sid: fc00:1::/64
    - host: Compute2 
      sid: fc00:2::/64
    - host: Compute3 
      sid: fc00:3::/64
    - host: Compute4 
      sid: fc00:4::/64

# System Infomation
config:
    mm_src_node: Compute1
    rules:
        - mm_dst_node: Compute4
          mm_src_addr: fd00:0:172:16:ffff::1/64
          vrf: 100
          transit_nodes:
            - Compute2
        - mm_dst_node: Compute4
          mm_src_addr: fd00:0:172:16:ffff::2/64
          vrf: 101
          transit_nodes:
            - Compute3 
        - mm_dst_node: Compute4
          mm_src_addr: fd00:0:172:16:ffff::3/64
          vrf: 102
          transit_nodes:
            - Compute2
            - Compute3


