# SID Information
nodes:
    - host: compute1 
      locator: fc00:1::/64
      node-sid: fc00:1::0
    - host: compute2 
      locator: fc00:2::/64
      node-sid: fc00:2::0
    - host: compute3 
      locator: fc00:3::/64
      node-sid: fc00:3::0
    - host: compute4 
      locator: fc00:4::/64
      node-sid: fc00:4::0
    - host: compute5
      locator: fc00:5::/64
      node-sid: fc00:5::0

# System Infomation
config:
    mm_src_node: compute1
    rules:
        - mm_dst_node: compute4
          mm_src_addr: fd00:0:172:16:ffff::1/64
          table: 100
          transit_nodes:
            - compute2
        - mm_dst_node: compute4
          mm_src_addr: fd00:0:172:16:ffff::2/64
          table: 101
          transit_nodes:
            - compute3 
        - mm_dst_node: compute4
          mm_src_addr: fd00:0:172:16:ffff::3/64
          table: 102
          transit_nodes:
            - compute2
            - compute3


