# Estimete Parameter
params:
    mm_src_node: compute1
    method: ptr
    packet_num: 60
    packet_size: 700
    repeat_num: 20
    # Number of measurements per time
    meas_num: 3
    # Simple moving average interval
    sma_interval: 3
