// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MeasureRequest_Method int32

const (
	MeasureRequest_IGI MeasureRequest_Method = 0
	MeasureRequest_PTR MeasureRequest_Method = 1
)

var MeasureRequest_Method_name = map[int32]string{
	0: "IGI",
	1: "PTR",
}

var MeasureRequest_Method_value = map[string]int32{
	"IGI": 0,
	"PTR": 1,
}

func (x MeasureRequest_Method) String() string {
	return proto.EnumName(MeasureRequest_Method_name, int32(x))
}

func (MeasureRequest_Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2, 0}
}

type SRInfo_SegFunc int32

const (
	SRInfo_H_ENCAP  SRInfo_SegFunc = 0
	SRInfo_H_INSERT SRInfo_SegFunc = 1
)

var SRInfo_SegFunc_name = map[int32]string{
	0: "H_ENCAP",
	1: "H_INSERT",
}

var SRInfo_SegFunc_value = map[string]int32{
	"H_ENCAP":  0,
	"H_INSERT": 1,
}

func (x SRInfo_SegFunc) String() string {
	return proto.EnumName(SRInfo_SegFunc_name, int32(x))
}

func (SRInfo_SegFunc) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5, 0}
}

//*
// Configure messages
type ConfigureRequest struct {
	IprouteInfo          []*IprouteInfo `protobuf:"bytes,1,rep,name=iproute_info,json=iprouteInfo,proto3" json:"iproute_info,omitempty"`
	SrInfo               []*SRInfo      `protobuf:"bytes,2,rep,name=sr_info,json=srInfo,proto3" json:"sr_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ConfigureRequest) Reset()         { *m = ConfigureRequest{} }
func (m *ConfigureRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigureRequest) ProtoMessage()    {}
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *ConfigureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigureRequest.Unmarshal(m, b)
}
func (m *ConfigureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigureRequest.Marshal(b, m, deterministic)
}
func (m *ConfigureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureRequest.Merge(m, src)
}
func (m *ConfigureRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigureRequest.Size(m)
}
func (m *ConfigureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureRequest proto.InternalMessageInfo

func (m *ConfigureRequest) GetIprouteInfo() []*IprouteInfo {
	if m != nil {
		return m.IprouteInfo
	}
	return nil
}

func (m *ConfigureRequest) GetSrInfo() []*SRInfo {
	if m != nil {
		return m.SrInfo
	}
	return nil
}

type ConfigureResponse struct {
	Time *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	// Types that are valid to be assigned to Code:
	//	*ConfigureResponse_Ok
	//	*ConfigureResponse_Error
	Code                 isConfigureResponse_Code `protobuf_oneof:"code"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ConfigureResponse) Reset()         { *m = ConfigureResponse{} }
func (m *ConfigureResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigureResponse) ProtoMessage()    {}
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *ConfigureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigureResponse.Unmarshal(m, b)
}
func (m *ConfigureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigureResponse.Marshal(b, m, deterministic)
}
func (m *ConfigureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureResponse.Merge(m, src)
}
func (m *ConfigureResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigureResponse.Size(m)
}
func (m *ConfigureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureResponse proto.InternalMessageInfo

func (m *ConfigureResponse) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type isConfigureResponse_Code interface {
	isConfigureResponse_Code()
}

type ConfigureResponse_Ok struct {
	Ok string `protobuf:"bytes,2,opt,name=ok,proto3,oneof"`
}

type ConfigureResponse_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ConfigureResponse_Ok) isConfigureResponse_Code() {}

func (*ConfigureResponse_Error) isConfigureResponse_Code() {}

func (m *ConfigureResponse) GetCode() isConfigureResponse_Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ConfigureResponse) GetOk() string {
	if x, ok := m.GetCode().(*ConfigureResponse_Ok); ok {
		return x.Ok
	}
	return ""
}

func (m *ConfigureResponse) GetError() string {
	if x, ok := m.GetCode().(*ConfigureResponse_Error); ok {
		return x.Error
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ConfigureResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ConfigureResponse_Ok)(nil),
		(*ConfigureResponse_Error)(nil),
	}
}

//
// Measure messages
type MeasureRequest struct {
	Method MeasureRequest_Method `protobuf:"varint,1,opt,name=method,proto3,enum=api.MeasureRequest_Method" json:"method,omitempty"`
	// Types that are valid to be assigned to Param:
	//	*MeasureRequest_IgiptrParam
	Param                isMeasureRequest_Param `protobuf_oneof:"param"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *MeasureRequest) Reset()         { *m = MeasureRequest{} }
func (m *MeasureRequest) String() string { return proto.CompactTextString(m) }
func (*MeasureRequest) ProtoMessage()    {}
func (*MeasureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *MeasureRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeasureRequest.Unmarshal(m, b)
}
func (m *MeasureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeasureRequest.Marshal(b, m, deterministic)
}
func (m *MeasureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeasureRequest.Merge(m, src)
}
func (m *MeasureRequest) XXX_Size() int {
	return xxx_messageInfo_MeasureRequest.Size(m)
}
func (m *MeasureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MeasureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MeasureRequest proto.InternalMessageInfo

func (m *MeasureRequest) GetMethod() MeasureRequest_Method {
	if m != nil {
		return m.Method
	}
	return MeasureRequest_IGI
}

type isMeasureRequest_Param interface {
	isMeasureRequest_Param()
}

type MeasureRequest_IgiptrParam struct {
	IgiptrParam *IgiPtrParam `protobuf:"bytes,2,opt,name=igiptr_param,json=igiptrParam,proto3,oneof"`
}

func (*MeasureRequest_IgiptrParam) isMeasureRequest_Param() {}

func (m *MeasureRequest) GetParam() isMeasureRequest_Param {
	if m != nil {
		return m.Param
	}
	return nil
}

func (m *MeasureRequest) GetIgiptrParam() *IgiPtrParam {
	if x, ok := m.GetParam().(*MeasureRequest_IgiptrParam); ok {
		return x.IgiptrParam
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MeasureRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MeasureRequest_IgiptrParam)(nil),
	}
}

type MeasureResponse struct {
	Result               []*Result `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MeasureResponse) Reset()         { *m = MeasureResponse{} }
func (m *MeasureResponse) String() string { return proto.CompactTextString(m) }
func (*MeasureResponse) ProtoMessage()    {}
func (*MeasureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *MeasureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeasureResponse.Unmarshal(m, b)
}
func (m *MeasureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeasureResponse.Marshal(b, m, deterministic)
}
func (m *MeasureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeasureResponse.Merge(m, src)
}
func (m *MeasureResponse) XXX_Size() int {
	return xxx_messageInfo_MeasureResponse.Size(m)
}
func (m *MeasureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MeasureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MeasureResponse proto.InternalMessageInfo

func (m *MeasureResponse) GetResult() []*Result {
	if m != nil {
		return m.Result
	}
	return nil
}

//
// Sub messages
type IprouteInfo struct {
	Ipv6Addr             string   `protobuf:"bytes,1,opt,name=ipv6_addr,json=ipv6Addr,proto3" json:"ipv6_addr,omitempty"`
	Vrf                  int32    `protobuf:"varint,2,opt,name=vrf,proto3" json:"vrf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IprouteInfo) Reset()         { *m = IprouteInfo{} }
func (m *IprouteInfo) String() string { return proto.CompactTextString(m) }
func (*IprouteInfo) ProtoMessage()    {}
func (*IprouteInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *IprouteInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IprouteInfo.Unmarshal(m, b)
}
func (m *IprouteInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IprouteInfo.Marshal(b, m, deterministic)
}
func (m *IprouteInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IprouteInfo.Merge(m, src)
}
func (m *IprouteInfo) XXX_Size() int {
	return xxx_messageInfo_IprouteInfo.Size(m)
}
func (m *IprouteInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_IprouteInfo.DiscardUnknown(m)
}

var xxx_messageInfo_IprouteInfo proto.InternalMessageInfo

func (m *IprouteInfo) GetIpv6Addr() string {
	if m != nil {
		return m.Ipv6Addr
	}
	return ""
}

func (m *IprouteInfo) GetVrf() int32 {
	if m != nil {
		return m.Vrf
	}
	return 0
}

type SRInfo struct {
	SrcAddr              string         `protobuf:"bytes,1,opt,name=src_addr,json=srcAddr,proto3" json:"src_addr,omitempty"`
	DstAddr              string         `protobuf:"bytes,2,opt,name=dst_addr,json=dstAddr,proto3" json:"dst_addr,omitempty"`
	SegFunc              SRInfo_SegFunc `protobuf:"varint,3,opt,name=seg_func,json=segFunc,proto3,enum=api.SRInfo_SegFunc" json:"seg_func,omitempty"`
	SidList              []string       `protobuf:"bytes,4,rep,name=sid_list,json=sidList,proto3" json:"sid_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SRInfo) Reset()         { *m = SRInfo{} }
func (m *SRInfo) String() string { return proto.CompactTextString(m) }
func (*SRInfo) ProtoMessage()    {}
func (*SRInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *SRInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SRInfo.Unmarshal(m, b)
}
func (m *SRInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SRInfo.Marshal(b, m, deterministic)
}
func (m *SRInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SRInfo.Merge(m, src)
}
func (m *SRInfo) XXX_Size() int {
	return xxx_messageInfo_SRInfo.Size(m)
}
func (m *SRInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SRInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SRInfo proto.InternalMessageInfo

func (m *SRInfo) GetSrcAddr() string {
	if m != nil {
		return m.SrcAddr
	}
	return ""
}

func (m *SRInfo) GetDstAddr() string {
	if m != nil {
		return m.DstAddr
	}
	return ""
}

func (m *SRInfo) GetSegFunc() SRInfo_SegFunc {
	if m != nil {
		return m.SegFunc
	}
	return SRInfo_H_ENCAP
}

func (m *SRInfo) GetSidList() []string {
	if m != nil {
		return m.SidList
	}
	return nil
}

type IgiPtrParam struct {
	ProbeNum             int32    `protobuf:"varint,1,opt,name=probe_num,json=probeNum,proto3" json:"probe_num,omitempty"`
	PacketSize           int32    `protobuf:"varint,2,opt,name=packet_size,json=packetSize,proto3" json:"packet_size,omitempty"`
	RepeatNum            int32    `protobuf:"varint,3,opt,name=repeat_num,json=repeatNum,proto3" json:"repeat_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IgiPtrParam) Reset()         { *m = IgiPtrParam{} }
func (m *IgiPtrParam) String() string { return proto.CompactTextString(m) }
func (*IgiPtrParam) ProtoMessage()    {}
func (*IgiPtrParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *IgiPtrParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IgiPtrParam.Unmarshal(m, b)
}
func (m *IgiPtrParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IgiPtrParam.Marshal(b, m, deterministic)
}
func (m *IgiPtrParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IgiPtrParam.Merge(m, src)
}
func (m *IgiPtrParam) XXX_Size() int {
	return xxx_messageInfo_IgiPtrParam.Size(m)
}
func (m *IgiPtrParam) XXX_DiscardUnknown() {
	xxx_messageInfo_IgiPtrParam.DiscardUnknown(m)
}

var xxx_messageInfo_IgiPtrParam proto.InternalMessageInfo

func (m *IgiPtrParam) GetProbeNum() int32 {
	if m != nil {
		return m.ProbeNum
	}
	return 0
}

func (m *IgiPtrParam) GetPacketSize() int32 {
	if m != nil {
		return m.PacketSize
	}
	return 0
}

func (m *IgiPtrParam) GetRepeatNum() int32 {
	if m != nil {
		return m.RepeatNum
	}
	return 0
}

type Result struct {
	MeasRes              float64              `protobuf:"fixed64,1,opt,name=meas_res,json=measRes,proto3" json:"meas_res,omitempty"`
	SidList              []string             `protobuf:"bytes,2,rep,name=sid_list,json=sidList,proto3" json:"sid_list,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetMeasRes() float64 {
	if m != nil {
		return m.MeasRes
	}
	return 0
}

func (m *Result) GetSidList() []string {
	if m != nil {
		return m.SidList
	}
	return nil
}

func (m *Result) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.MeasureRequest_Method", MeasureRequest_Method_name, MeasureRequest_Method_value)
	proto.RegisterEnum("api.SRInfo_SegFunc", SRInfo_SegFunc_name, SRInfo_SegFunc_value)
	proto.RegisterType((*ConfigureRequest)(nil), "api.ConfigureRequest")
	proto.RegisterType((*ConfigureResponse)(nil), "api.ConfigureResponse")
	proto.RegisterType((*MeasureRequest)(nil), "api.MeasureRequest")
	proto.RegisterType((*MeasureResponse)(nil), "api.MeasureResponse")
	proto.RegisterType((*IprouteInfo)(nil), "api.IprouteInfo")
	proto.RegisterType((*SRInfo)(nil), "api.SRInfo")
	proto.RegisterType((*IgiPtrParam)(nil), "api.IgiPtrParam")
	proto.RegisterType((*Result)(nil), "api.Result")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 643 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x41, 0x4f, 0xdb, 0x4c,
	0x10, 0x8d, 0x63, 0x62, 0x27, 0x63, 0x3e, 0x3e, 0x77, 0x69, 0x51, 0x48, 0x55, 0x11, 0xb9, 0x1c,
	0xb8, 0xe0, 0x48, 0xa1, 0xe5, 0x50, 0xf5, 0x02, 0x88, 0x36, 0x91, 0x4a, 0x14, 0x6d, 0x38, 0xf5,
	0x62, 0x39, 0xf6, 0xc6, 0x6c, 0x83, 0xbd, 0xdb, 0xdd, 0x35, 0x12, 0xe9, 0x9f, 0xe9, 0x3f, 0xe8,
	0x5f, 0xac, 0xbc, 0x6b, 0xd2, 0x04, 0xf5, 0xd0, 0x93, 0x77, 0xdf, 0xbc, 0xf1, 0xbc, 0x79, 0x33,
	0x0b, 0xff, 0x49, 0x22, 0x1e, 0x68, 0x42, 0x42, 0x2e, 0x98, 0x62, 0xc8, 0x8e, 0x39, 0xed, 0x1d,
	0x65, 0x8c, 0x65, 0xf7, 0x64, 0xa0, 0xa1, 0x79, 0xb9, 0x18, 0x28, 0x9a, 0x13, 0xa9, 0xe2, 0x9c,
	0x1b, 0x56, 0x90, 0x83, 0x7f, 0xc5, 0x8a, 0x05, 0xcd, 0x4a, 0x41, 0x30, 0xf9, 0x5e, 0x12, 0xa9,
	0xd0, 0x19, 0xec, 0x52, 0x2e, 0x58, 0xa9, 0x48, 0x44, 0x8b, 0x05, 0xeb, 0x5a, 0x7d, 0xfb, 0xc4,
	0x1b, 0xfa, 0x61, 0xcc, 0x69, 0x38, 0x36, 0x81, 0x71, 0xb1, 0x60, 0xd8, 0xa3, 0x7f, 0x2e, 0xe8,
	0x18, 0x5c, 0x29, 0x0c, 0xbf, 0xa9, 0xf9, 0x9e, 0xe6, 0xcf, 0xb0, 0xa6, 0x3a, 0x52, 0x54, 0xdf,
	0xa0, 0x84, 0x17, 0x1b, 0xe5, 0x24, 0x67, 0x85, 0x24, 0x28, 0x84, 0x9d, 0x4a, 0x56, 0xd7, 0xea,
	0x5b, 0x27, 0xde, 0xb0, 0x17, 0x1a, 0xcd, 0xe1, 0x93, 0xe6, 0xf0, 0xf6, 0x49, 0x33, 0xd6, 0x3c,
	0xe4, 0x43, 0x93, 0x2d, 0xbb, 0xcd, 0xbe, 0x75, 0xd2, 0x19, 0x35, 0x70, 0x93, 0x2d, 0xd1, 0x01,
	0xb4, 0x88, 0x10, 0x4c, 0x74, 0xed, 0x1a, 0x34, 0xd7, 0x4b, 0x07, 0x76, 0x12, 0x96, 0x92, 0xe0,
	0xa7, 0x05, 0x7b, 0x37, 0x24, 0x96, 0x1b, 0x4d, 0x0e, 0xc1, 0xc9, 0x89, 0xba, 0x63, 0xa9, 0x2e,
	0xbb, 0x37, 0xec, 0x69, 0xb9, 0xdb, 0xa4, 0xf0, 0x46, 0x33, 0x70, 0xcd, 0x44, 0xef, 0x61, 0x97,
	0x66, 0x94, 0x2b, 0x11, 0xf1, 0x58, 0xc4, 0xb9, 0x96, 0xb0, 0x36, 0x26, 0xa3, 0x53, 0x25, 0xa6,
	0x15, 0x3e, 0x6a, 0x60, 0xcf, 0xf0, 0xf4, 0x35, 0xe8, 0x81, 0x63, 0x7e, 0x84, 0x5c, 0xb0, 0xc7,
	0x9f, 0xc7, 0x7e, 0xa3, 0x3a, 0x4c, 0x6f, 0xb1, 0x6f, 0x5d, 0xba, 0xd0, 0xd2, 0xff, 0x0a, 0xce,
	0xe1, 0xff, 0x75, 0xf1, 0xda, 0x97, 0xb7, 0xe0, 0x08, 0x22, 0xcb, 0x7b, 0x55, 0x4f, 0xc0, 0x38,
	0x8a, 0x35, 0x84, 0xeb, 0x50, 0xf0, 0x11, 0xbc, 0x8d, 0x99, 0xa0, 0xd7, 0xd0, 0xa1, 0xfc, 0xe1,
	0x3c, 0x8a, 0xd3, 0x54, 0xe8, 0xce, 0x3a, 0xb8, 0x5d, 0x01, 0x17, 0x69, 0x2a, 0x90, 0x0f, 0xf6,
	0x83, 0x58, 0x68, 0xd9, 0x2d, 0x5c, 0x1d, 0x83, 0x5f, 0x16, 0x38, 0x66, 0x44, 0xe8, 0x10, 0xda,
	0x52, 0x24, 0x9b, 0x89, 0xae, 0x14, 0x89, 0xce, 0x3b, 0x84, 0x76, 0x2a, 0x95, 0x09, 0x35, 0x4d,
	0x28, 0x95, 0x4a, 0x87, 0x42, 0x68, 0x4b, 0x92, 0x45, 0x8b, 0xb2, 0x48, 0xb4, 0xf9, 0x7b, 0xc3,
	0xfd, 0x8d, 0xb9, 0x87, 0x33, 0x92, 0x7d, 0x2a, 0x8b, 0x04, 0xbb, 0xd2, 0x1c, 0x74, 0x15, 0x9a,
	0x46, 0xf7, 0x54, 0xaa, 0xee, 0x4e, 0xdf, 0xd6, 0x55, 0x68, 0xfa, 0x85, 0x4a, 0x15, 0x1c, 0x83,
	0x5b, 0xd3, 0x91, 0x07, 0xee, 0x28, 0xba, 0x9e, 0x5c, 0x5d, 0x4c, 0xfd, 0x06, 0xda, 0x85, 0xf6,
	0x28, 0x1a, 0x4f, 0x66, 0xd7, 0xf8, 0xd6, 0xb7, 0x82, 0x6f, 0xe0, 0x6d, 0x58, 0x5d, 0xf5, 0xcb,
	0x05, 0x9b, 0x93, 0xa8, 0x28, 0x73, 0x2d, 0xbb, 0x85, 0xdb, 0x1a, 0x98, 0x94, 0x39, 0x3a, 0x02,
	0x8f, 0xc7, 0xc9, 0x92, 0xa8, 0x48, 0xd2, 0x15, 0xa9, 0xfb, 0x06, 0x03, 0xcd, 0xe8, 0x8a, 0xa0,
	0x37, 0x00, 0x82, 0x70, 0x12, 0x2b, 0x9d, 0x6e, 0xeb, 0x78, 0xc7, 0x20, 0x93, 0x32, 0x0f, 0x0a,
	0x70, 0x8c, 0xdb, 0x95, 0xec, 0x9c, 0xc4, 0x32, 0x12, 0x44, 0xea, 0x2a, 0x16, 0x76, 0xab, 0x3b,
	0x26, 0x72, 0xab, 0xa3, 0xe6, 0x56, 0x47, 0xeb, 0xc5, 0xb6, 0xff, 0x6d, 0xb1, 0x87, 0x3f, 0x2a,
	0x07, 0xf4, 0x1b, 0x46, 0x1f, 0xa0, 0xb3, 0x7e, 0x28, 0xe8, 0x95, 0xb6, 0xf4, 0xf9, 0x3b, 0xed,
	0x1d, 0x3c, 0x87, 0xeb, 0xbd, 0x79, 0x07, 0x6e, 0xbd, 0x4a, 0x68, 0xff, 0x2f, 0x5b, 0xdd, 0x7b,
	0xb9, 0x0d, 0x9a, 0xac, 0xcb, 0xe0, 0x6b, 0x3f, 0xa3, 0xea, 0xae, 0x9c, 0x87, 0x09, 0xcb, 0x07,
	0x8f, 0xa7, 0xcb, 0x55, 0x3e, 0x20, 0x85, 0x48, 0x4f, 0xe5, 0xa3, 0x54, 0x24, 0x1f, 0xc4, 0x9c,
	0xce, 0x1d, 0x2d, 0xfd, 0xec, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xfa, 0xbf, 0x34, 0x6b,
	0x04, 0x00, 0x00,
}
